### ISSUE TITLE
Speichern von JS-Dateien aus dem Assets-Ordner erfolgt nicht

### ISSUE THREAD

**Issue by basistom** [netzmacht/contao-theme-plus#100]
- Contao: 3.5.6
- Theme-Plus: dev-support/4.x

Das Speichern der Quelldatei für neue JS-Dateien erfolgt nicht korrekt wenn als Quelle "assets" ausgewählt ist. Es erscheint keine Fehlermeldung. Im Filetree ist die zuvor ausgewählte Datei nicht mehr ausgewählt.

**Comment by frontendschlampe** [comment]
Den Fehler kann ich bestätigen. Das Problem tritt immer auf, wenn nicht der Filepicker in der Lightbox geöffnet wird (bei files), sondern auf der Seite die Dateiauswahl erfolgt (bei allen anderen Quellen, außer files). Man kann die Datei auswählen, speichern und aus dem Datensatz rausgehen. Die Datei ist auch gespeichert, aber wenn man den Datensatz erneut bearbeitet, ist die zuvor ausgewählte Datei nicht mehr ausgewählt. Das Problem tritt auch bei der Dateiauswahl von CSS-Dateien auf.

Contao 3.5.6, netzmacht/contao-theme-plus 4.4.5

**Comment by dmolineus** [comment]
Liegt an einem Bug in Contao. PR ist gestellt: https://github.com/contao/core/pull/8562

**Comment by dmolineus** [comment]
Wird mit Contao 3.5.19 behoben sein. Schließe das Ticket daher.
