### ISSUE TITLE
Deprecated Notice bei der Auswahl weiterer Stylesheets/Javascripts in der Seitenstruktur

### ISSUE THREAD

**Issue by frontendschlampe** [netzmacht/contao-theme-plus#101]
Wenn man in der Seitenstruktur unter den "Layout-Einstellungen" > "weitere Stylesheets …" oder "weitere Javascripts …" aktiviert, kommt folgende Meldung:

`Deprecated notice: Deprecated, use Bit3\Contao\ThemePlus\Model\StylesheetModel instead in composer/vendor/netzmacht/contao-theme-plus/deprecated/ThemePlus/Model/StylesheetModel.php on line 14
#0 [internal function]: __error(16384, 'Deprecated, use...', '/srv/web/XXX...', 14, Array)
#1 composer/vendor/netzmacht/contao-theme-plus/deprecated/ThemePlus/Model/StylesheetModel.php(14): trigger_error('Deprecated, use...', 16384)
#2 vendor/composer/ClassLoader.php(412): include('/srv/web/XXX...')
#3 vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/web/XXX...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('ThemePlus\Model...')
#5 composer/vendor/netzmacht/contao-theme-plus/src/Bit3/Contao/ThemePlus/DataContainer/Page.php(27): spl_autoload_call('ThemePlus\Model...')
#6 system/modules/core/library/Contao/Widget.php(1388): Bit3\Contao\ThemePlus\DataContainer\Page->getStylesheets(Object(Contao\DC_Table))
#7 system/modules/core/classes/DataContainer.php(265): Contao\Widget::getAttributesFromDca(Array, 'theme_plus_styl...', NULL, 'theme_plus_styl...', 'tl_page', Object(Contao\DC_Table))
#8 system/modules/core/drivers/DC_Table.php(1945): Contao\DataContainer->row('{title_legend},...')
#9 system/modules/core/classes/Ajax.php(387): Contao\DC_Table->edit(false, 'sub_theme_plus_...')
#10 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#11 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('page')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}`

bzw.

`Deprecated notice: Deprecated, use Bit3\Contao\ThemePlus\Model\JavaScriptModel instead in composer/vendor/netzmacht/contao-theme-plus/deprecated/ThemePlus/Model/JavaScriptModel.php on line 14
#0 [internal function]: __error(16384, 'Deprecated, use...', '/srv/web/XXX...', 14, Array)
#1 composer/vendor/netzmacht/contao-theme-plus/deprecated/ThemePlus/Model/JavaScriptModel.php(14): trigger_error('Deprecated, use...', 16384)
#2 vendor/composer/ClassLoader.php(412): include('/srv/web/XXX...')
#3 vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/web/XXX...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('ThemePlus\Model...')
#5 composer/vendor/netzmacht/contao-theme-plus/src/Bit3/Contao/ThemePlus/DataContainer/Page.php(36): spl_autoload_call('ThemePlus\Model...')
#6 system/modules/core/library/Contao/Widget.php(1388): Bit3\Contao\ThemePlus\DataContainer\Page->getJavaScripts(Object(Contao\DC_Table))
#7 system/modules/core/classes/DataContainer.php(265): Contao\Widget::getAttributesFromDca(Array, 'theme_plus_java...', NULL, 'theme_plus_java...', 'tl_page', Object(Contao\DC_Table))
#8 system/modules/core/drivers/DC_Table.php(1945): Contao\DataContainer->row('{title_legend},...')
#9 system/modules/core/classes/Ajax.php(387): Contao\DC_Table->edit(false, 'sub_theme_plus_...')
#10 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#11 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('page')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}`

Nach dem Speichern endet das dann in einer weißen Seite, wo dann nur noch die Meldung erscheint. Es tritt natürlich nur auf, wenn "Fehlermeldungen anzeigen" aktiviert ist, aber das ist sehr nervend, gerade auf Entwicklungssystemen.

Contao 3.5.6, netzmacht/contao-theme-plus 4.4.5

**Comment by basistom** [comment]
+1

**Comment by dmolineus** [comment]
Fixed in https://github.com/netzmacht/contao-theme-plus/commit/6d0375f7d92311d12ebe1b364591cd7083891fdc. Gonna release new bugfix release today.
