### ISSUE TITLE
contao-twig for Theme+ 4 not compatible with PHP7

### ISSUE THREAD

**Issue by rflx** [netzmacht/contao-theme-plus#103]
Hi folks

I'm running into follow issue after installing contao-theme-plus with contao-twig on Contao 3.5.17 with PHP7:
`Fatal error: Uncaught exception Error with message Function name must be a string thrown in composer/vendor/bit3/contao-twig/src/ContaoTwig/TwigBackendTemplate.php on line 60
#0 composer/vendor/bit3/contao-twig/src/ContaoTwig/TwigBackendModule.php(39): TwigBackendTemplate->parse()
#1 composer/vendor/bit3/contao-assetic/src/ContaoAssetic/AsseticConfigModule.php(65): TwigBackendModule->generate()
#2 system/modules/core/classes/Backend.php(423): ContaoAssetic\AsseticConfigModule->generate()
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('assetic_config')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}`

netzmacht/contao-theme-plus 4.4.5
bit3/contao-assetic 1.4
bit3/contao-twig 1.11

How can i get rid of this? Is there a workaround for PHP7?
I'm using the default bit3 packages with contao-theme-plus due that contao-assetic 2.0 is not supported within contao-theme-plus 4.

Thanks and cheers!

**Comment by dmolineus** [comment]
This is a bug of https://github.com/contao-community-alliance/twig. I let this ticket open until it is fixed there.

**Comment by rflx** [comment]
Hi @dmolineus 
Thank you for updating contao-assetic and contao-theme-plus.
This PHP issue can be fixed with my pull request https://github.com/bit3archive/contao-twig/pull/1/commits/2acc6ff59339c89b482400cf692718893e357e71. I've forked the wrong repository (bit3archive/twig) and was unable to pull it into the actual repository (contao-community-alliance/twig).

**Comment by dmolineus** [comment]
Fixed with https://github.com/contao-community-alliance/twig/releases/tag/1.12.1
