### ISSUE TITLE
Externe Files fetchen

### ISSUE THREAD

**Issue by andreasisaak** [netzmacht/contao-theme-plus#15]
Externe Files werden bei der Komprimierung nicht berücksichtigt. Als Idee stand im Raum die Contao Request Klasse zu verwenden (vielleicht sogar httprequestextended von Xtra?) und den Fetch externer Dateien nur optional via BE zu aktivieren.

Probleme:

- wie kann man tracken das sich externe Files geändert haben
- wie kann man verhindern das es zum Timeout kommt

**Comment by dmolineus** [comment]
Spätestens seit Theme+ 5 (bei 4 weiß ich es gerade nicht), werden externe Assets geladen. 
https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Asset/HttpAsset.php#L69

Es wird der Last-Modified Header ausgewertet. Probleme mit dem Timeout sind zur Zeit nicht berücksichtigt. 

Dennoch schließe ich das Issue, da grundsätzlich implementiert.
