### ISSUE TITLE
Kopieren von Dateien in ein anderes Theme klappt nicht

### ISSUE THREAD

**Issue by tristanlins** [netzmacht/contao-theme-plus#21]
Wenn ich meine angelegten Dateien über "mehrere bearbeiten" in ein anderes Theme kopieren möchte, dann wird nur die oberste Datei in das neue Theme kopiert, alle anderen aber nochmals in das eigene.

https://www.contao-community.de/showthread.php?30188-Kopieren-von-Dateien-in-ein-anderes-Theme-klappt-nicht

**Comment by dmolineus** [comment]
Konnte nicht reproduziert werden (v4). Vermutlich inzwischen gefixed. Falls noch aktuell, bitte neu öffnen.
