### ISSUE TITLE
exclude im dca setzten

### ISSUE THREAD

**Issue by FlxPeters** [netzmacht/contao-theme-plus#27]
https://github.com/InfinitySoft/ThemePlus/blob/2.x/src/system/modules/theme_plus/dca/tl_page.php#L28

Felder können nicht für Benutzer/Gruppen ausgeschlossen werden. 

``` php
$GLOBALS['TL_DCA']['tl_page']['fields']['theme_plus_include_files'] = array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_page']['theme_plus_include_files'],
	'inputType'               => 'checkbox',
    'exclude'               => true,
	'eval'                    => array('submitOnChange'=>true, 'tl_class'=>'long')
);
```

**Comment by dmolineus** [comment]
The current version has the exclude flags. https://github.com/netzmacht/contao-theme-plus/blob/master/contao/dca/tl_page.php

If any is missed, feel free to reopen.
