### ISSUE TITLE
MultiColumnWizard anstelle von MultiTextWizard

### ISSUE THREAD

**Issue by andreasisaak** [netzmacht/contao-theme-plus#29]
Theme+ 3.0 verwendet noch den MultiTextWizard, vielleicht könnte man das mal auf den MCW ändern. Dann wäre man flexibler und der TextWizard wäre irgendwann auch mal obsolet.

Man hat in den meisten Fällen ja sowieso den MCW in der Installation

**Comment by dmolineus** [comment]
Der MultiTextWizard wird aktuell (Theme+ 5) nicht mehr verwendet.
