### ISSUE TITLE
contao.css wird immer eingebunden

### ISSUE THREAD

**Issue by MacKP** [netzmacht/contao-theme-plus#51]
Leider wird aktuell die contao.css immer eingebunden (auch wenn man die Haken setzt, das es nicht gemacht werden soll). Auch über Filter bekommt man das Verhalten nicht weg. Sobald man ausgeloggt ist, wird die contao.css auch dann wieder eingebunden.

Viele Grüße

Hier der passende Thread: 
https://community.contao.org/de/showthread.php?35157-contao-css-wird-eingebunden-anderes-Verhalten-als-in-Contao-2-11-6&p=271274#post271274

**Comment by dmolineus** [comment]
Meines Erachtens ist dies nicht mehr aktuell. Wenn doch, bitte wieder öffnen.
