### ISSUE TITLE
JS wird nicht in "mobile" Layouts eingebunden

### ISSUE THREAD

**Issue by mediabakery** [netzmacht/contao-theme-plus#52]
Wird ein Layout als Layout für mobile Seiten eingebunden werden zwar alle über T+ eingebundene CSS Dateien übernommen, aber keine JS.
C 3.1.1

**Comment by dmolineus** [comment]
Ist dieses Problem noch aktuellen Version von Theme+ 4 und 5RC1?

**Comment by dmolineus** [comment]
Theme+ hatte grundsätzlich das mobile Layout ingoriert. Behoben in 4fbef81dab339ba528eda263c0499c8083e073e8.
