### ISSUE TITLE
Auswahl für das Einbinden weiterer Dateien in "Startpunkt einer Website" fehlt

### ISSUE THREAD

**Issue by frontendschlampe** [netzmacht/contao-theme-plus#60]
bei den anderen Seitentypen gibt es die Auswahl noch, nur nicht in der o.g., was aber eigentlich sehr wichtig ist! Contao 3.2 RC1

**Comment by dmolineus** [comment]
Ich kann das Problem nicht reproduzieren (T+ 4). Vermutlich bereits behoben. Wenn es noch auftritt, bitte Ticket wieder öffnen.
