### ISSUE TITLE
Theme+ Developer Toool aktueller Master Brunch mit Contao 3.2.1

### ISSUE THREAD

**Issue by bruc13** [netzmacht/contao-theme-plus#62]
Um die Theme+ Developer Toool zu sehen müsste ich maneuell die varibale auf true setzen. Sonst wird immer die zusammengefasste Datei ausgegeben.
Assetic auch das aktuellste aus dem Master branch.

``public static function isDesignerMode()
	{
		return static::getInstance()->blnLiveMode
			? true
			: true;
	}
``

Dann wird bei mir immer hinter jedem Script oder CSS eingefügt:

``Fatal error: Exception thrown without a stack frame in Unknown on line 0
``

Kommt noch eine Version für Contao 3.2 ins ER? 
Das Composer ist noch nicht ausgereift, läuft bei mir nicht mal unter Xampp PHP 5.4 Windows 7.
Danke

**Comment by dmolineus** [comment]
Ist das Problem noch aktuell?

**Comment by dmolineus** [comment]
Aufgrund fehlener Rückmeldung geschlossen. Besteht das Problem weiterhin, bitte erneut öffnen.
