### ISSUE TITLE
allow protocol relative URLs

### ISSUE THREAD

**Issue by backbone87** [netzmacht/contao-theme-plus#72]
der preg an dieser stelle müsste angepasst werden:

https://github.com/bit3/contao-theme-plus/blob/master/src/ThemePlus/ThemePlus.php#L1352

**Comment by backbone87** [comment]
wurde das gefixt oder ist das invalid inzwischen?

**Comment by dmolineus** [comment]
Wurde gefixt wie im Ticket #99 beschrieben.
