### ISSUE TITLE
Pfad zum Compass verkleinern

### ISSUE THREAD

**Issue by andreasisaak** [netzmacht/contao-theme-plus#80]
Derzeit muss man für die Integration von Compass noch folgenden Pfad angeben:

https://github.com/andreasisaak/contao-boilerplate/blob/master/files/standard/layout/scss/style.scss#L1

Es wäre aber schön wenn man nur "compass" nehmen könnte :)

**Comment by dmolineus** [comment]
Ist das Problem noch relevant? In dem verlinkten Beispiel ist nur "compass" angegeben.

**Comment by andreasisaak** [comment]
Da siehst du ihn noch:

https://github.com/andreasisaak/contao-boilerplate/commit/500a4a0af2d3f8b7e26a9f1c3c0764bed9afac42

Für mich hat sich das Problem erledigt, da ich kein compass mehr nutze ;)

**Comment by dmolineus** [comment]
Da sich sonst niemand hier eingeklingt hat und Nutzung von Compass generell nachlässt, belasse ich dies so wie es ist.
