### ISSUE TITLE
Contao 3.3.3 und theme-plus 4.4 Cache problem 

### ISSUE THREAD

**Issue by bruc13** [netzmacht/contao-theme-plus#83]
Hi,
ich nutze Beide Cachemethoden und seit dem Update zur Contao 3.3. wird die Home Seite, die auch ohne Alias (parameter) aufgerufen werden kann  - z.B. https://github.com, ohne CSS und JS Ausgegeben. 
Habt ihr eine Idee warum?

**Comment by dmolineus** [comment]
Existiert das Problem weiterhin?

**Comment by davidmaack** [comment]
Ja, das Problem besteht weiterhin :).

Beim Output werden die Methode replaceDynamicScriptTags() zweimal aufgerufen. Einmal in der Methode addToCache() und direkt danach in der eigentlichen output-Methode. Theme-Plus baut hier per Hook die Assets zusammenbaut und damit Contao die Dateien nicht noch einmal verwendet, werden die Arrays TL_JAVASCRIPT, TL_CSS usw. geleert. Beim zweiten Durchlauf des Hooks fehlen dann halt ein paar Dateien :)

Als ersten Workaround habe ich mich in den Hook getCacheKey gehängt und sicher die Werte für TL_JAVACSRIPT und TL_CSS weg (mehr brauchte ich gerade nicht). Beim zweiten Durchlauf von replaceDynamicScriptTags() konnte ich die Werte somit wieder herstellen. Wirklich elegant ist das nicht, hat aber funktioniert :D

**Comment by fritzmg** [comment]
Habe dasselbe Problem auf http://stats.spikx.net/mwll.html bspw. Dort ist der Seitencache aktiviert und jQuery fehlt beim ersten Ladevorgang im kombinierten JavaScript file (vermutlich dann wenn die Seite für den Cache generiert wird). Beim zweiten Ladevorgang ist jQuery dann wieder dabei.

Scheint aber tatsächlich erst in neueren Contao Versionen zu passieren. Eine andere Seite von mir, die noch unter Contao 3.2.21 läuft, hat auch den Seitencache aktiviert, dort gibt es aber nie Probleme mit fehlenden JavaScripts.

Wäre nett wenn das gefixt wird, ansonsten ist Theme+ für aktuelle Contao Versionen ja nicht mehr benutzbar, wenn man den Seitencache braucht.

**Comment by markusmilkereit** [comment]
Im referenzierten Beitrag habe ich eine Lösung vorgeschlagen, die das Problem aus der Welt schafft:

Ich habe jetzt meinen Code an einen Hook früher in der Kette gehängt: statt an `replaceDynamicScriptTags` wird meine Login jetzt im Hook `outputFrontendTemplate` bearbeitet - damit funktioniert alles wie erwartet.

**Comment by dmolineus** [comment]
Kann das Problem unter 3.5.18 nicht mehr nachstellen. Tritt es bei euch noch auf?

**Comment by davidmaack** [comment]
Also bei einer 3.5.17 ist es die Tage bei uns noch aufgetreten. Da sich am Core an den entsprechenden Stellen aber nichts verändert hat, würde es mich wundern, wenn das Problem weg wäre.

**Comment by dmolineus** [comment]
Hab mir das Problem nochmal angeschaut und konnte es nun auch nachstellen. c40af4c188b91763b105a82b4458f5696de2e1cf sollte das Problem beheben.

Bitte testet dies mal im Fix-Branch https://github.com/netzmacht/contao-theme-plus/tree/fix/page-cache-issue und gebt hier Rückmeldung.

**Comment by fritzmg** [comment]
Seems to work :)

**Comment by dmolineus** [comment]
> Seems to work :)

Gerade 4.4.7 veröffentlicht, dass den Bugfix beinhaltet.
