### ISSUE TITLE
externe URL's in Verbindung mit v5 RC1

### ISSUE THREAD

**Issue by frontendschlampe** [netzmacht/contao-theme-plus#92]
ich hab Theme+ 5.0.0 RC1 und delahaye/dlh_googlemaps 2.0.9, sowie Contao 3.2.19 - wenn ich jetzt eine Karte einbinden möchte kommt folgende Fehlermeldung:

`````` php
Fatal error: Uncaught exception RuntimeException with message The source file "/srv/web/musterkunde/srv/staging/htdocs/http://maps.google.com/maps/api/js?language=de&sensor=false" does not exist. thrown in composer/vendor/kriswallsmith/assetic/src/Assetic/Asset/FileAsset.php on line 73```
``````

**Comment by dmolineus** [comment]
This should fix it. Please test it and give some feedback.

**Comment by frontendschlampe** [comment]
ähm ... naja ... jetzt kommt zumindest keine Fehlermeldung mehr ;-)

Aber das Script wird trotzdem nicht korrekt eingebunden, denn jetzt wird `http://staging.meine-domain.de/assets/js/ef5f80f2-js?language=de&sensor=false.js` statt `http://maps.google.com/maps/api/js?language=de&sensor=false`eingebunden, aber die `http://staging.meine-domain.de/assets/js/ef5f80f2-js?language=de&sensor=false.js` gibt es nicht - 404 in der Konsole - Google Map funzt nicht

**Comment by dmolineus** [comment]
Theme+ kommt wohl mit den Query-Parameter nicht klar (?language=de&sensor=false). Lass mich raten, die Datei `assets/js/ef5f80f2-js?language=de&sensor=false.js` existiert in dem Ordner.

Bei meinem Test hatte ich einen Pfad ohne Paramter.

**Comment by dmolineus** [comment]
Fixed in 945dacb435d00ae9dbd4dcb76a5114e2cc06cc31.
