### ISSUE TITLE
Problem with composer update

### ISSUE THREAD

**Issue by fritzmg** [netzmacht/contao-theme-plus#94]
It seems the old `bit3/contao-theme-plus` repository has been removed completely now. This causes a severe issue if you have a version of `bit3/contao-theme-plus` installed that is lower than `4.4.3` and if you are starting a package update in the package manager of Contao. Composer then deletes the old version of `bit3/contao-theme-plus` and tries to install `bit3/contao-theme-plus (4.4.3)` - however, this is not possible anymore:

```
 - Removing bit3/contao-theme-plus (4.3.5)
 - Installing bit3/contao-theme-plus (4.4.3)
   Downloading: Connecting...

 [Composer\Downloader\TransportException]
 The "https://api.github.com/repos/bit3/contao-theme-plus/zipball/fba2013fb66121fb7885be8da4d74f982980821c" file could not be downloaded (HTTP/1.1 404 Not Found)
```

In theory composer should replace it with `netzmacht/contao-theme-plus`, but the new repository does not have any of the old release tags, so composer cannot do that, I guess.

And if you do it manually, you can only select the dev branches (dev-4.x, dev-5.0.x, dev-5.1.x).

**Comment by dmolineus** [comment]
Just release version 4.4.4 so that a tagged version exists. It's identical to bit3/contao-theme-plus 4.4.3. Would be great if you can test it. https://github.com/netzmacht/contao-theme-plus/releases/tag/4.4.4

**Comment by bytehead** [comment]
Cool, thanks! What do you think of adding `bit3/contao-theme-plus` to the `replaces` section?

**Comment by fritzmg** [comment]
Everything seems fine :). Though the require section still references `bit3/contao-assetic` and `bit3/contao-meta-palettes`.

**Comment by dmolineus** [comment]
> Cool, thanks! What do you think of adding bit3/contao-theme-plus to the replaces section?

Ohm, you're right. Only the master/develop branch has the replacement statement so far.

**Comment by dmolineus** [comment]
Dependencies got updated in 4.4.5. Only contao-assetic still depends on the bit3 variant as the netzmacht/contao-assetic currently only support v2.
