### ISSUE TITLE
No differentiation in the integration of files in standard & mobile layout

### ISSUE THREAD

**Issue by intrio** [netzmacht/contao-theme-plus#95]
T+ integrates always all files of the Standard Layout when generating a page in the molbile Layout, regardless to the selected files in the mobile page layout.

**Comment by dmolineus** [comment]
Commit 4fbef81dab339ba528eda263c0499c8083e073e8 should fix it. Would be great if you test it (branch support/4.x) and give feedback if everything works fine now.

**Comment by dmolineus** [comment]
Bugfix got released in 4.4.5
