### ISSUE TITLE
Problem with external StyleSheet and https

### ISSUE THREAD

**Issue by frontendschlampe** [netzmacht/contao-theme-plus#99]
I include

`//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css`

as Stylesheet via URL with the option "Load URL" and my website is reached via https. The css will be loaded but the external font files will be blocked because the request is via http.

`[Warning] [blocked] The page at https://meine-domain.de was not allowed to display insecure content from http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.woff?v=4.4.0.`

Deactivating the option "Load URL" everything is fine.

**Comment by frontendschlampe** [comment]
Contao 3.5.3 and Theme+ 4.4.5

**Comment by dmolineus** [comment]
Bei meinem Setup wird nicht einmal versucht von //maxcdn.bootstrapcdn.com/font-awesome zu laden, sondern von localhost. Hast du einen Assetic-Filter im Einsatz, der die URLs korrigiert?

**Comment by kocd** [comment]
We have probably a related problem. If we add files via `$GLOBALS['TL_CSS'][] = '//domain.com/file`  we get an runtime error: `Uncaught exception RuntimeException with message The source file "/home/domains/domain.lan/public_html///code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css" does not exist`.

Perhaps it is related to line 1433 in ThemePlus.php which excludes protocol relative urls.

**Comment by dmolineus** [comment]
@kocd Commit 39dd569 should fix your issue. Would be great if you can test it (Branch support/4.x).

**Comment by kocd** [comment]
@dmolineus patch works like expected in our environment. Thank you.

**Comment by dmolineus** [comment]
Als jetzige Lösung habe ich dies so geändert, dass Urls beginnend mit "//" als https:// interpretiert werden. Dadurch umgehe ich mögliche Probleme mit eventuell unterschiedlichen Cache-Dateien je nach HTTP-Protokoll. Sollte es Probleme damit geben, bitte reporten.
